/**
 * Preset Starter Templates for Aura Page Builder
 */
export const STARTER_TEMPLATES = [
  {
    id: "saas-launchpad",
    name: "SaaS Product Launchpad",
    category: "SaaS & AI",
    badge: "Popular",
    description: "High-converting SaaS landing page with Hero, Feature grid, Stats, Pricing tables, FAQ, and Footer.",
    previewColor: "from-cyan-500 via-indigo-600 to-purple-600",
    theme: "aura",
    fontFamily: "Inter",
    bgColor: "#070a12",
    textColor: "#f8fafc",
    blocks: [
      {
        id: "block-hero-saas",
        type: "hero",
        content: {
          title: "Build & Scale AI Apps at Lightning Speed",
          subTitle: "The all-in-one developer platform for launching production-grade web applications in minutes, not months.",
          buttonText: "Start Free Trial 🚀",
          secondaryButtonText: "Watch Demo 🎥",
          buttonLink: "/auth/signup",
          imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
        },
      },
      {
        id: "block-stats-saas",
        type: "stats",
        content: {
          title: "Trusted by Modern Engineering Teams",
          subTitle: "Powering thousands of high-traffic web applications worldwide.",
          stat1Value: "99.99%",
          stat1Label: "Uptime SLA",
          stat2Value: "10M+",
          stat2Label: "Daily Requests",
          stat3Value: "500ms",
          stat3Label: "Avg Latency",
        },
      },
      {
        id: "block-features-saas",
        type: "features",
        content: {
          title: "Everything You Need to Scale",
          subTitle: "Architected for extreme performance, security, and developer productivity.",
          feature1Title: "Instant Deployment",
          feature1Desc: "Push to Git and deploy live edge endpoints worldwide within seconds.",
          feature2Title: "Built-in Analytics",
          feature2Desc: "Real-time user insights, error tracking, and performance metrics.",
          feature3Title: "Enterprise Security",
          feature3Desc: "SOC2 Type II compliant with end-to-end payload encryption.",
        },
      },
      {
        id: "block-pricing-saas",
        type: "pricing",
        content: {
          title: "Flexible Pricing for Every Team",
          subTitle: "Start free and scale as you grow. No hidden charges.",
          plan1Name: "Starter",
          plan1Price: "$0",
          plan1Period: "/month",
          plan1Features: "Up to 3 Pages, Community Support, Standard Speed",
          plan2Name: "Pro SaaS",
          plan2Price: "$29",
          plan2Period: "/month",
          plan2Features: "Unlimited Pages, Priority SLA, Custom Domains, 24/7 Support",
          plan2Popular: true,
          plan3Name: "Enterprise",
          plan3Price: "$99",
          plan3Period: "/month",
          plan3Features: "Dedicated Cluster, Custom SSO, SLA Guarantee, SAML Auth",
        },
      },
      {
        id: "block-faq-saas",
        type: "faq",
        content: {
          title: "Frequently Asked Questions",
          subTitle: "Got questions? We've got answers.",
          q1: "Can I cancel my subscription anytime?",
          a1: "Yes, you can upgrade, downgrade, or cancel your subscription at any time directly from your dashboard.",
          q2: "Do I need coding experience to use this?",
          a2: "No coding is required! Our visual drag-and-drop studio lets you compose pages effortlessly.",
        },
      },
    ],
  },
  {
    id: "creative-portfolio",
    name: "Creative Developer Portfolio",
    category: "Portfolio",
    badge: "Trending",
    description: "Sleek portfolio layout featuring Hero intro, Works showcase, Skills highlights, Testimonials, and Contact form.",
    previewColor: "from-purple-500 via-pink-500 to-rose-600",
    theme: "cyberpunk",
    fontFamily: "Outfit",
    bgColor: "#090d16",
    textColor: "#f1f5f9",
    blocks: [
      {
        id: "block-hero-portfolio",
        type: "hero",
        content: {
          title: "Full-Stack Engineer & Product Designer",
          subTitle: "Crafting beautiful, high-performance web applications and digital experiences with modern web technologies.",
          buttonText: "View Featured Works ⚡",
          secondaryButtonText: "Get in Touch ✉️",
          buttonLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
        },
      },
      {
        id: "block-gallery-portfolio",
        type: "gallery",
        content: {
          title: "Selected Client Projects",
          subTitle: "A curated collection of web apps, SaaS dashboards, and design systems.",
          img1Url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80",
          img1Caption: "Fintech Dashboard UI",
          img2Url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80",
          img2Caption: "E-Commerce Design System",
          img3Url: "https://images.unsplash.com/photo-1522542550221-31fd19575a2d?auto=format&fit=crop&w=600&q=80",
          img3Caption: "AI Creative Studio App",
        },
      },
      {
        id: "block-testimonials-portfolio",
        type: "testimonials",
        content: {
          title: "Client Testimonials",
          subTitle: "What founders and engineering leaders say about working together.",
          quote1: "Harshil transformed our complex cloud platform into an intuitive, ultra-fast web product. Highly recommended!",
          author1: "Alex Rivera",
          role1: "CTO at CloudScale Inc",
          quote2: "Extremely detail-oriented with world-class frontend execution. Delivered ahead of deadline.",
          author2: "Sarah Chen",
          role2: "Founder at Nexus Studio",
        },
      },
      {
        id: "block-form-portfolio",
        type: "form",
        content: {
          title: "Let's Build Something Amazing Together",
          subTitle: "Have a project in mind or looking for a lead developer? Send a message below.",
          buttonText: "Send Message 🚀",
        },
      },
    ],
  },
  {
    id: "event-countdown",
    name: "Tech Summit & Event Registration",
    category: "Events",
    badge: "New",
    description: "High-energy event landing page with Countdown banner, Speaker stats, Agenda features, and Ticket registration form.",
    previewColor: "from-emerald-500 via-teal-600 to-cyan-600",
    theme: "emerald",
    fontFamily: "Roboto",
    bgColor: "#061312",
    textColor: "#f0fdf4",
    blocks: [
      {
        id: "block-hero-event",
        type: "hero",
        content: {
          title: "Global AI & Web Developers Summit 2026",
          subTitle: "Join 5,000+ engineers, founders, and creators for 3 days of inspiring keynotes, workshops, and networking.",
          buttonText: "Register Your Spot 🎫",
          secondaryButtonText: "Explore Speakers 🎤",
          buttonLink: "#register",
          imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
        },
      },
      {
        id: "block-stats-event",
        type: "stats",
        content: {
          title: "Event Highlights at a Glance",
          subTitle: "Everything coming to the biggest web summit of the year.",
          stat1Value: "30+",
          stat1Label: "World-Class Speakers",
          stat2Value: "3 Days",
          stat2Label: "Hands-on Workshops",
          stat3Value: "5,000+",
          stat3Label: "Global Attendees",
        },
      },
      {
        id: "block-form-event",
        type: "form",
        content: {
          title: "Claim Your Ticket Now",
          subTitle: "Early bird tickets are limited. Register today to lock in 50% discount.",
          buttonText: "Complete Registration 🎟️",
        },
      },
    ],
  },
  {
    id: "agency-landing",
    name: "Digital Product Agency",
    category: "Agency",
    badge: "Popular",
    description: "Professional digital agency site with Hero banner, Client Logo Cloud, Services list, and Consultation form.",
    previewColor: "from-amber-500 via-orange-600 to-red-600",
    theme: "sunset",
    fontFamily: "Inter",
    bgColor: "#140a07",
    textColor: "#fff7ed",
    blocks: [
      {
        id: "block-hero-agency",
        type: "hero",
        content: {
          title: "We Build High-Impact Digital Products",
          subTitle: "Full-cycle software engineering, UX design, and cloud architecture for ambitious startups and brands.",
          buttonText: "Book Free Discovery Call 🚀",
          secondaryButtonText: "Our Services 🛠️",
          buttonLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
        },
      },
      {
        id: "block-logocloud-agency",
        type: "logoCloud",
        content: {
          title: "Trusted by Industry Leaders Worldwide",
          subTitle: "Partnering with category-defining companies to build web software.",
        },
      },
      {
        id: "block-features-agency",
        type: "features",
        content: {
          title: "Core Services",
          subTitle: "End-to-end technical capabilities from concept to scale.",
          feature1Title: "Web App Development",
          feature1Desc: "Modern Next.js & React web applications with robust backend APIs.",
          feature2Title: "UI/UX Design Systems",
          feature2Desc: "Pixel-perfect interfaces designed for engagement and conversions.",
          feature3Title: "Cloud & DevOps",
          feature3Desc: "Scalable Kubernetes, Vercel, and AWS cloud infrastructure.",
        },
      },
      {
        id: "block-form-agency",
        type: "form",
        content: {
          title: "Book Your 30-Min Strategy Call",
          subTitle: "Discuss your product roadmap with our senior engineering architects.",
          buttonText: "Schedule Call 📞",
        },
      },
    ],
  },
];
